### ISSUE TITLE
Sign packages

### ISSUE THREAD

**Issue by sharpenedblade** [Redecorating/archlinux-t2-packages#1]
Sign the packages with a private key, right now anyone can MITM the connection to GitHub and install arbitrary packages. Follow https://docs.github.com/en/actions/security-guides/encrypted-secrets, and add your private key as a secret. Then make the CI sign the packages, and publish `*.sig` files to `repo`. You do not need to sign the database, even the official repo does not.

**Comment by Redecorating** [comment]
> right now anyone can MITM the connection to GitHub

is pacman using http? Or is there a way to break https? I guess "Digi Cert Inc" could create a certificate or something.

I probably won't be able to get it working tonight but I'll try to get it to sign the packages.

**Comment by Redecorating** [comment]
if the changes i've pushed build, this should be the public key, but won't be able to check if it works for a while after when it should:tm: finish building.
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGIUx2QBDADgfCe58jjZxzPanmKhcikEyAT9ywVHsUWzfQSsVt5ZlNYpPEAq
t2w5mevEy243NAXq2KCvlQn+mRCX4ki/hmVpwjO/xglkjYbbTTazSfLRyUyyl1v2
Q+XMFX7x5mkOEgkkRN6QMr0TkAlVgayeYxLcWOGrL7WhCHPjJPpcCuOB4wvMJSis
b4NgwtyXpJOqcu00GCveM6L+bIqTONagmEsMdkbSZCKQElKj5UX1bQvKhIh5WHRs
md977V4FlplJ1OhbmDKQ5W8ZGeOBkY4fleqHVaXsU7G9IP4wu46mgUEKxsNEM5cu
ogBSqGt/nDylVaOzbWbrDi+fFc37nOMpsv/f4B5xPQdExeoFTdH5/ASJkSyxDTX7
LSFQrxZfPv8Js8NbNi1Nx+R0zDE1zyw9IVfoYz0Rf8CyoMEA1+OKmIg3pPjnPKQg
uPhwVJ/9UyEGQGL8PFmz1IUO/pXNZCJbGUtKylLSyRLPyzfRWFreM8nga4cQ2GX/
7ltDAmb+USGEb3MAEQEAAbReUmVkZWNvcmF0aW5nIChUbyBiZSBzdG9yZWQgb24g
Z2l0aHViIHNlY3JldHMpIDw2OTgyNzUxNCtSZWRlY29yYXRpbmdAdXNlcnMubm9y
ZXBseS5naXRodWIuY29tPokB0wQTAQgAPhYhBPHllNxPSGxNBOy0P9638SG6qm9O
BQJiFMdkAhsDBQkBsw8ABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEN638SG6
qm9OrwgL+L6FHaP663ua8/ZXxWtwpUulQq3+rwbkY2YjKwSQlE/yxw745n8xsqty
YBk9D7H8DAm5/8hgzccfFU/efSrXiwicfOm+7+ciQddKrVdd8CPb8pqfel+Rq9ka
XmNBRArtF3eXhJ+vd/ZcepYXB+GaDAqFgKfFXUs/WRnejwjSRnD2FmTAJIf1KMnW
BVQGFwW3gyXx4oORjk3BiOAM1N3hH1NSXiGLlFrJEkpROAu1YyvniTwIDR0UHspz
6CLjTtY3koZ0Nlu8Vj88cQtk4dKxWqNwWIgFN60W9+lVAxTjSzUesEiLRvoH5Jc9
N4+sjt9Z9T3oiVakGOrYCWprlBD96CuxSdnp10NHYCowFQOgeyjPXvVYbuigNzHn
nsUk+B7XvqHgfemSpm961HRZ+nxWY1XnT1q0oN6EWqHCnvtfaUC7LEQIZvyYs3O9
Gn4nqwgwB5R1GORGJNvLfmQSNX7F/5bgIw01MezD+xgGKehuiUQqlpIn/krE7UUa
YRpYLVaI
=jO5q
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by sharpenedblade** [comment]
> > right now anyone can MITM the connection to GitHub
> 
> is pacman using http? Or is there a way to break https? I guess "Digi Cert Inc" could create a certificate or something.

https is not secure for this use case, though the chance of GitHubs cert getting exposed i far less than most of the official mirrors. Pacman is not designed around https for package authenticity, Someone *could* add a malicious package to the database file, and pacman would think it is normal becuase this repo has to be `trustall`.

**Comment by sharpenedblade** [comment]
You need to upload your public key to a key server like `keyservers.ubuntu.com` or `pgp.mit/edu`. These are federated keyservers, so a key uploaded there will be mirrored to other keyservers everywhere. I can upload it for you if you want

**Comment by Redecorating** [comment]
https://pgp.mit.edu/pks/lookup?op=vindex&search=0xDEB7F121BAAA6F4E

**Comment by Redecorating** [comment]
I'll change instructions on the readme when I get time. I think I'll have to put the command to import the key onto the readme so that text could be modified if someone man in the middle'd github.

**Comment by sharpenedblade** [comment]
Signing is fully working for me, closing.
