### ISSUE TITLE
linux-t2: signature is unknown trust

### ISSUE THREAD

**Issue by jokoso** [Redecorating/archlinux-t2-packages#10]
Hello

Firstly, thank you very much for all your work towards enabling us to run Arch on our T2 Macs!

This morning I ran into the following error while upgrading:

```
error: linux-t2: signature from "Redecorating (To be stored on github secrets) <69827514+Redecorating@users.noreply.github.com>" is unknown trust
:: File /var/cache/pacman/pkg/linux-t2-6.1.8-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

I've tried `pacman-key --refresh-keys` to no avail, and now I'm considering setting `SigLevel = Never` in `/etc/pacman.conf`.

How would you suggest I proceed?

Kind regards,
Jon

**Comment by Redecorating** [comment]
I've moved your issue here because it's with the repo and signing, not the package itself. I think your issue was caused by me changing the keys recently as they expired.

Please try this and see if that helps you update:
```
sudo pacman-key -d F1E594DC4F486C4D04ECB43FDEB7F121BAAA6F4E
sudo pacman-key --recv-keys F1E594DC4F486C4D04ECB43FDEB7F121BAAA6F4E --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key F1E594DC4F486C4D04ECB43FDEB7F121BAAA6F4E
sudo pacman -Syu
```

**Comment by jokoso** [comment]
Ah, that explains it. Thank you!
