### ISSUE TITLE
GPG trust issues

### ISSUE THREAD

**Issue by Jeidnx** [Redecorating/archlinux-t2-packages#4]
Hello there,

I just added the repository to my arch install and while trying to install / update anything i kept getting the following error message:
`Error: linux-t2-docs: signature from "Redecorating (To be stored on github secrets) <69827514+Redecorating@users.noreply.github.com>" is unknown trust`

not quite sure what the root cause of this is, but running `sudo pacman-key --lsign-key DEB7F121BAAA6F4E` fixed it for me. The readme states that the key would be auto imported by pacman, which in my case didn't happen. I would suggest adding something like this to the readme:

> To manually add the key run the following commands: 
> ```
> sudo pacman-keys --recv-key  DEB7F121BAAA6F4E
> sudo pacman-key --lsign-key DEB7F121BAAA6F4E
> ```

As i said, not quite sure if this is a me problem only, but if you want i will gladly make a pull request with these changes.

**Comment by Redecorating** [comment]
Maybe upstream changes to pacman make it not prompt to download the keys anymore? Or possibly there's something in the Options = line.

Could you check if your entry in /etc/pacman.conf is the same as the example in the readme? If it isn't the same could you see if changing it to what's in the readme fixes the issue?

If it doesn't turn out to be caused by something in the /etc/pacman.conf repo entry, a pr with the changes you described would be great.

**Comment by Jeidnx** [comment]
Ok this is a bit embarrassing. After changing some seemingly non related lines in my pacman.conf i get prompted to install the key properly. I have no clue why and can't seem to reproduce the Issue now.

When the entry in pacman.conf is not correct, pacman -Syu hard fails and i copy pasted the entry from the readme, so i am pretty convinced that this was not the culprit.

The only explanation i have is that pacman was unable to find the key on the keyserver. Maybe it had an outage or something similar? But then why would running `pacman-keys --recv-key` manually find the key?

Regardless, think having the manual Instructions won't hurt and maybe save a handful of people the troubleshooting i did. I will make a PR with the changes shortly.

Also a bit off topic, maybe a separate Issue would be appropriate, i don't think GitHub likes being used as a hosting service, I've heard of some issues with this in the past. As much as i love your project with the sub-modules and GitHub actions to fully automate the updates, I would consider hosting this on a dedicated Server.

**Comment by Redecorating** [comment]
This was really meant to be a temporary repo. I'm hoping we'll get newer packages on dl.t2linux.org, and then I won't need to worry about updating this or github removing this.

On getting a dedicated server for this, I don't own one or have an income to rent one with, so I don't think I'd be able to do that (but hopefully it won't be needed)
