### ISSUE TITLE
Error building wifi firmware package

### ISSUE THREAD

**Issue by Jeidnx** [Redecorating/archlinux-t2-packages#6]
Not quite sure if this is the right place, would appreciate getting pointed in the right direction if this is the case.

When trying to build the apple-bcm-wifi-firmware i get build errors from the python module:

```
==> Starting build()...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jeidnx/archlinux-t2-packages/wifi-fw/src/asahi-installer/src/firmware/wifi.py", line 139, in <module>
    col = WiFiFWCollection(sys.argv[1])
  File "/home/jeidnx/archlinux-t2-packages/wifi-fw/src/asahi-installer/src/firmware/wifi.py", line 37, in __init__
    self.load(source_path)
  File "/home/jeidnx/archlinux-t2-packages/wifi-fw/src/asahi-installer/src/firmware/wifi.py", line 57, in load
    k, v = i.split("-", 1)
ValueError: not enough values to unpack (expected 2, got 1)
==> ERROR: A failure occurred in build().
```

I have the firmware-source.tar in the right directory and got it from the ./get-fw.sh aswell as from a real macOs environment.

**Comment by Redecorating** [comment]
I'm not sure why it is broken now, but you could grab this which was built before the python script stopped working https://mirror.funami.tech/arch-mact2/os/x86_64/apple-bcm-wifi-firmware-12.0-1-any.pkg.tar.zst also the t2linux wiki page has a new wifi script that should work, if you want to do that instead

**Comment by Jeidnx** [comment]
Thanks for linking the package!

I am aware of the t2linux script, but it only works if you have a working macOS on the __same device__ you are trying to install the wifi firmware on. Also I find not having to reboot the machine twice a very compelling case for this package - booting in and out of macOS always takes ages.

I very much understand why you wouldn't want to fix / maintain this script - you never know when apple changes something which completely breaks it.

For now this Issue is resolved for me, although in my opinion it should either be fixed or omitted entirely.
