### ISSUE TITLE
Touchbar don't work after suspend, because of a bug in script file.

### ISSUE THREAD

**Issue by syo093c** [Redecorating/archlinux-t2-packages#9]
![Screenshot from 2022-08-03 23-13-43](https://user-images.githubusercontent.com/45763662/182647372-225b245e-f332-4356-8140-965fb9ad9a3e.png)

 "rm-apple-ib-tb.sh" is used to prevent errors of sleep,
 but the script is not correct, cause it is not functional.

[rm-apple-ib-tb.sh](https://github.com/Redecorating/archlinux-t2-packages/blob/main/apple-ibridge-dkms-git/rm-apple-ib-tb.sh)
The shell script is missing "#" to indicates using sh as shell.

Please also see this document about suspend in T2 linux,
[fixing-suspend](https://wiki.t2linux.org/guides/dkms/#fixing-suspend)

I have made a pull request (#8) for this, thank you!

**Comment by Redecorating** [comment]
96b695fc6cd56b1f087d2b24842ec477a4946ab8
